# Generated by Django 5.0 on 2024-01-16 17:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('zhanr', models.CharField(max_length=20)),
                ('running_time', models.CharField(max_length=10)),
                ('photo', models.ImageField(default='A Dreamy World Wallpaper  (15).jpg', upload_to='')),
                ('point', models.CharField(max_length=10)),
                ('discription', models.TextField()),
                ('limit_age', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=datetime.datetime(2024, 1, 16, 20, 57, 26, 942310))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
