# Generated by Django 5.0 on 2024-01-19 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 17, 24, 6, 445727)),
        ),
    ]
